### ISSUE TITLE
龙芯设备编译syncthing报错 v1.18.0

### ISSUE THREAD

**Issue by wuta12** [loongson/go#3]
### What version of Go are you using (`go version`)?

<pre>
$ go version
root@admin-pc:~/syncthing-1.18.0# go version
go version go1.15.6 linux/loong64

</pre>

### Does this issue reproduce with the latest release?
是的

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
root@admin-pc:~/syncthing-1.18.0# go env
GO111MODULE="on"
GOARCH="loong64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="loong64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="http://goproxy.loongnix.cn:3000"
GOROOT="/usr/lib/go-1.15"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.15/pkg/tool/linux_loong64"
GCCGO="gccgo"
GOLOONG64="hardfloat"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/syncthing-1.18.0/go.mod"
CGO_CFLAGS="-O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2"
CGO_FFLAGS="-O2"
CGO_LDFLAGS="-O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=lp64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build358318297=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

1.下载syncthing1.18的源码（https://github.com/syncthing/syncthing/tree/v1.18.0）
2.cd进入syncthing1.18源码目录
3.rm go.sum
4.配置源
go env -w GOPROXY=http://goproxy.loongnix.cn:3000
5.关闭校验
go env -w GOSUMDB=off
6.go run build.go

### What did you expect to see?

编译通过

### What did you see instead?
编译报错，具体见附件
[龙芯设备编译syncthing报错.txt](https://github.com/loongson/go/files/7452495/syncthing.txt)

**Comment by MariaBombardier** [comment]
应该是没有达到1.16最低版本的要求。
等吧，又要猴年马月才能等龙芯的Loongnix源里更新golang

**Comment by chenguoqi-cc** [comment]
> 应该是没有达到1.16最低版本的要求。 等吧，又要猴年马月才能等龙芯的Loongnix源里更新golang

Loongnix server 8.3: dnf install golang-1.18

**Comment by MariaBombardier** [comment]
> > 应该是没有达到1.16最低版本的要求。 等吧，又要猴年马月才能等龙芯的Loongnix源里更新golang
> 
> Loongnix server 8.3: dnf install golang-1.18

Thx，不过我现在暂时用不到了，其他人要用到的还在等新世界的Golang。。。
