### ISSUE TITLE
编译loong64-master的时候遇到自举编译器crash

### ISSUE THREAD

**Issue by Rabenda** [loongson/go#5]
```
Building Go cmd/dist using /usr/lib/go-1.15. (go1.15.6 linux/loong64)
Building Go toolchain1 using /usr/lib/go-1.15.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go tool dist: FAILED: */go/pkg/tool/linux_loong64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: signal: segmentation fault (core dumped)
```

commit-id： b049fa2841355dd55cd059c66978cb35c8502ba5

**Comment by Rabenda** [comment]
```
[125191.382205] do_page_fault(): sending SIGSEGV to go_bootstrap for invalid write access to 00000000000000f1
[125191.382225] epc = 0000000000079940 in go_bootstrap[10000+384000]
[125191.382255] ra  = 000000000004a4cc in go_bootstrap[10000+384000]
```

**Comment by chenguoqi-cc** [comment]
请问你用的系统是是那个？ 这个loong64-master分支目前我们用的系统是:   https://github.com/sunhaiyong1978/CLFS-for-LoongArch/releases/tag/2.3

**Comment by n1ght2** [comment]
麒麟系统上遇到了相同的问题

**Comment by Rabenda** [comment]
> 麒麟系统上遇到了相同的问题

我搞出来了 不要用原系统的golang 需要现在其他机器上交叉出来go-bootstrap 然后用这个bootstrap在la机器上继续编译

```
# x86
GOOS=linux GOARCH=loong64 ./bootstrap.bash
# 产出 go-linux-loong64-bootstrap.tbz 放到la机器上
# la 解压设定 GOROOT_BOOTSTRAP
export GOROOT_BOOTSTRAP= <prefix>/go-linux-loong64-bootstrap
# 进入src目录
bash -x all.bash
```

**Comment by chenguoqi-cc** [comment]
> 麒麟系统上遇到了相同的问题

loong64-master分支是针对社区内核的版本， 无法兼容的是产品版本的loongnix系统，麒麟系统等。

**Comment by n1ght2** [comment]
> > 麒麟系统上遇到了相同的问题
> 
> 我搞出来了 不要用原系统的golang 需要现在其他机器上交叉出来go-bootstrap 然后用这个bootstrap在la机器上继续编译
> 
> ```
> # x86
> GOOS=linux GOARCH=loong64 ./bootstrap.bash
> # 产出 go-linux-loong64-bootstrap.tbz 放到la机器上
> # la 解压设定 GOROOT_BOOTSTRAP
> export GOROOT_BOOTSTRAP= <prefix>/go-linux-loong64-bootstrap
> # 进入src目录
> bash -x all.bash
> ```

请问x86系统是啥？
按照这个流程，我用麒麟v10_x86交叉编译出来的go-linux-loong64-bootstrap里面的二进制放到LA平台一运行就提示“段错误”。

**Comment by Rabenda** [comment]
> > > 麒麟系统上遇到了相同的问题
> > 
> > 
> > 我搞出来了 不要用原系统的golang 需要现在其他机器上交叉出来go-bootstrap 然后用这个bootstrap在la机器上继续编译
> > ```
> > # x86
> > GOOS=linux GOARCH=loong64 ./bootstrap.bash
> > # 产出 go-linux-loong64-bootstrap.tbz 放到la机器上
> > # la 解压设定 GOROOT_BOOTSTRAP
> > export GOROOT_BOOTSTRAP= <prefix>/go-linux-loong64-bootstrap
> > # 进入src目录
> > bash -x all.bash
> > ```
> 
> 请问x86系统是啥？ 按照这个流程，我用麒麟v10_x86交叉编译出来的go-linux-loong64-bootstrap里面的二进制放到LA平台一运行就提示“段错误”。

我用gentoo go是1.17.6版本做的

**Comment by Rabenda** [comment]
> 请问你用的系统是是那个？ 这个loong64-master分支目前我们用的系统是: https://github.com/sunhaiyong1978/CLFS-for-LoongArch/releases/tag/2.3

我使用UOS编译的 这个master以后都不兼容UOS/Kylin之类的系统吗？

**Comment by chenguoqi-cc** [comment]
> > 请问你用的系统是是那个？ 这个loong64-master分支目前我们用的系统是: https://github.com/sunhaiyong1978/CLFS-for-LoongArch/releases/tag/2.3
> 
> 我使用UOS编译的 这个master以后都不兼容UOS/Kylin之类的系统吗？

目前是不兼容的了。

**Comment by n1ght2** [comment]
> 

请问后续是否有对Kylin、UOS、Loongnix的支持计划呢？因为现在有些软件编译时需要Go1.16+

**Comment by n1ght2** [comment]
> Collaborator

请问后续是否有对Kylin、UOS、Loongnix的支持计划呢？因为现在有些软件编译时需要Go1.16+

**Comment by Rabenda** [comment]
> > Collaborator
> 
> 请问后续是否有对Kylin、UOS、Loongnix的支持计划呢？因为现在有些软件编译时需要Go1.16+

我这边的方法是改sys/net包 缺少的系统包向1.15添加 大部分都是可以的

**Comment by chenguoqi-cc** [comment]
> 
Loongnix-server 8.3:  dnf install golang-1.18

**Comment by chenguoqi-cc** [comment]
> > Collaborator
> 
> 请问后续是否有对Kylin、UOS、Loongnix的支持计划呢？因为现在有些软件编译时需要Go1.16+

Loongnix server 8.3:   dnf install golang-1.18

**Comment by ReVe1uv** [comment]
> > > Collaborator
> > 
> > 
> > 请问后续是否有对Kylin、UOS、Loongnix的支持计划呢？因为现在有些软件编译时需要Go1.16+
> 
> Loongnix server 8.3: dnf install golang-1.18

感谢告知

**Comment by Clansty** [comment]
我在 CLFS 3.0 上编译的时候，无论如何都会出现总线错误。使用的是使用本仓库源码在 x86 上编译 bootstrap 包放到龙芯机器上继续编译的方法，也试了别人制作的 bootstrap 包

```
$ uname -a
Linux Sunhaiyong 5.17.0-rc1 #1 SMP PREEMPT Mon Feb 28 07:11:55 UTC 2022 loongarch64 GNU/Linux
```

[报错信息](https://0w.al/rjFsQRByaYkBZMJxbEmrKzJR)

**Comment by chenguoqi-cc** [comment]
>
go的源码已经更新， 目前可以使用了！

**Comment by Clansty** [comment]
> > 
> 
> go的源码已经更新， 目前可以使用了！

嗯嗯，我上个星期尝试再次编译已经成功了，并且成功编译了 frp。虽然 sys 和 net 库还需要替换
