### ISSUE TITLE
affected/package: LoongArch平台编译loong64-master分支源码时报错

### ISSUE THREAD

**Issue by n1ght2** [loongson/go#7]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/loong64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="loong64"
GOBIN=""
GOCACHE="/home/wq/.cache/go-build"
GOENV="/home/wq/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="loong64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/wq/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wq/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_loong64"
GCCGO="gccgo"
GOLOONG64="hardfloat"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2"
CGO_FFLAGS="-O2"
CGO_LDFLAGS="-O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=lp64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build925002043=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

./make.bash -v

### What did you expect to see?

编译通过

**Comment by chenguoqi-cc** [comment]
> 

loong64-master分支是针对社区内核的版本， 无法兼容的是产品版本的loongnix系统，麒麟系统等。
